variable_empty
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Determines if a variable is empty or not.

If the variable is empty, *true* is returned, *false* is returned otherwise.

.. literalinclude :: ../../tests/test-playbook-plugin.yml
   :language: yaml
   :start-after: plugin-util-variable-empty-01-start
   :end-before: plugin-util-variable-empty-01-end

.. literalinclude :: ../../tests/test-playbook-plugin.yml
   :language: yaml
   :start-after: plugin-util-variable-empty-02-start
   :end-before: plugin-util-variable-empty-02-end