variable_path
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Determines if a variable is an existing path or not.

If the variable is an existing path, *true* is returned, *false* is returned
otherwise.

.. literalinclude :: ../../tests/test-playbook-plugin.yml
   :language: yaml
   :start-after: plugin-util-variable-path-01-start
   :end-before: plugin-util-variable-path-01-end

.. literalinclude :: ../../tests/test-playbook-plugin.yml
   :language: yaml
   :start-after: plugin-util-variable-path-02-start
   :end-before: plugin-util-variable-path-02-end