variable_url
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Determines if a variable is an URL or not.

If the variable is an URL, *true* is returned, *false* is returned otherwise.

.. literalinclude :: ../../tests/test-playbook-plugin.yml
   :language: yaml
   :start-after: plugin-util-variable-url-01-start
   :end-before: plugin-util-variable-url-01-end

.. literalinclude :: ../../tests/test-playbook-plugin.yml
   :language: yaml
   :start-after: plugin-util-variable-url-02-start
   :end-before: plugin-util-variable-url-02-end