variable_collection
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Determines if a variable is a collection or not.

If the variable is a collection, *true* is returned, *false* is returned
otherwise.

.. literalinclude :: ../../tests/test-playbook-plugin.yml
   :language: yaml
   :start-after: plugin-util-variable-collection-01-start
   :end-before: plugin-util-variable-collection-01-end

.. literalinclude :: ../../tests/test-playbook-plugin.yml
   :language: yaml
   :start-after: plugin-util-variable-collection-02-start
   :end-before: plugin-util-variable-collection-02-end