---
# Tasks to update the apt cache.

- name: Update apt cache.
  debug:
    msg:
      - '--------------------------------------------------------------------'
      - 'Updating apt cache ...'
      - '--------------------------------------------------------------------'

- name: Update APT cache.
  command: apt update
  register: result
  retries: 2
  until: result is success
  changed_when: false