---
# Tasks to update the apt cache.

- name: Update apt cache.
  debug:
    msg:
      - '--------------------------------------------------------------------'
      - 'Updating apt cache ...'
      - '--------------------------------------------------------------------'

- name: Update the apt cache.
  apt:
    update_cache: true
  register: result
  retries: 2
  until: result is success
  changed_when: false