---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Setting up test environment.
      debug:
        msg:
          - '==============================================================='
          - 'Pre tasks'
          - '==============================================================='

    - name: Update APT cache.
      apt:
        update_cache: true
      register: result
      retries: 2
      until: result is success
      changed_when: false

    - name: Ensure Python requirements installed.
      apt:
        name:
          - python
          - python-pip
          - python-setuptools
          - python3-pip
          - python3-setuptools
        state: present

    - name: Ensure Pip requirements installed.
      pip:
        name:
          - flake8
          - requests
      changed_when: false

  roles:
    - role: unify
      vars:
        - validate: true
        - update: true
        - items:
            - https://is.gd/mgDWWk
            - https://is.gd/iN07fl

        - titles: items
        - expand: true
        - secondary: true
        - items_b:
            - [1, 2, 3]
            - [4, 5, 6]
            - https://is.gd/7lYPpb
        - titles_b: items
        - expand_b: true

  post_tasks:
    - name: Run verification tests.
      debug:
        msg:
          - '================================================================'
          - 'Post tasks'
          - '================================================================'

    - name: Get flake8 version.
      command: flake8 --version
      register: lint_version
      changed_when: false
      failed_when: lint_version is not search('pyflakes')